USE [master]
GO

/****** Object:  Database [ASPNET]    Script Date: 09.09.2014 14:51:46 ******/
CREATE DATABASE [ASPNET]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ASPNET', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.DOCS2014\MSSQL\DATA\ASPNET.mdf' , SIZE = 5120KB , MAXSIZE = 512000KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ASPNET_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.DOCS2014\MSSQL\DATA\ASPNET_log.ldf' , SIZE = 1024KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ASPNET].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ASPNET] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ASPNET] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ASPNET] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ASPNET] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ASPNET] SET ARITHABORT OFF 
GO

ALTER DATABASE [ASPNET] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ASPNET] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ASPNET] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [ASPNET] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ASPNET] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ASPNET] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ASPNET] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ASPNET] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ASPNET] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ASPNET] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ASPNET] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ASPNET] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [ASPNET] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ASPNET] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ASPNET] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ASPNET] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ASPNET] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ASPNET] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ASPNET] SET RECOVERY FULL 
GO

ALTER DATABASE [ASPNET] SET  MULTI_USER 
GO

ALTER DATABASE [ASPNET] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ASPNET] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ASPNET] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ASPNET] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ASPNET] SET  READ_WRITE 
GO


